
{"level":"error","message":"Forever detected script was killed by signal: SIGKILL"}
(node:3043103) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Started with the following options:
{
  debug: true,
  mitmIp: '10.0.3.1',
  autoAccess: true,
  autoAccessCache: 5000,
  maxAttemptsPerConnection: 6,
  sshServerIdentifier: 'SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2',
  containerMountPathPrefix: '/var/lib/lxc',
  containerMountPathSuffix: 'rootfs/',
  loggingAttackerStreams: '/home/student/MITM/logs/session_streams',
  loggingAuthenticationAttempts: '/home/student/MITM/logs/authentication_attempts',
  loggingLogins: '/home/student/MITM/logs/logins',
  loggingKeystrokes: '/home/student/MITM/logs/keystrokes',
  containerName: 'DATABASE_4',
  containerIp: '10.0.3.155',
  mitmPort: 1003,
  autoAccessFixed: 1
}
2022-10-23 01:13:14.168 - [Info] MITM Version: 2
2022-10-23 01:13:14.170 - [Info] Auto Access Enabled: true
2022-10-23 01:13:14.171 - [Debug] [Init] Auto Access Theshold Achieved: false
2022-10-23 01:13:14.181 - [Info] SSH man-in-the-middle server for 10.0.3.155 listening on 10.0.3.1:1003
2022-10-23 01:16:54.066 - [Debug] [Connection] Attacker connected: 34.133.67.239 | Client Identification: SSH-2.0-Go
2022-10-23 01:16:54.067 - [Debug] [Connection] Attacker connected: 34.133.67.239 | Client Identification: SSH-2.0-Go
2022-10-23 01:16:54.074 - [Debug] [Connection] Attacker connected: 34.133.67.239 | Client Identification: SSH-2.0-Go
2022-10-23 01:16:54.075 - [Debug] [Connection] Attacker connected: 34.133.67.239 | Client Identification: SSH-2.0-Go
2022-10-23 01:16:54.076 - [Debug] [Connection] Attacker connected: 34.133.67.239 | Client Identification: SSH-2.0-Go
2022-10-23 01:16:54.076 - [Debug] [Connection] Attacker connected: 34.133.67.239 | Client Identification: SSH-2.0-Go
2022-10-23 01:16:54.077 - [Debug] [Connection] Attacker connected: 34.133.67.239 | Client Identification: SSH-2.0-Go
2022-10-23 01:16:54.077 - [Debug] [Connection] Attacker connected: 34.133.67.239 | Client Identification: SSH-2.0-Go
2022-10-23 01:16:54.081 - [Debug] [Connection] Attacker connected: 34.133.67.239 | Client Identification: SSH-2.0-Go
2022-10-23 01:16:54.082 - [Debug] [Connection] Attacker connected: 34.133.67.239 | Client Identification: SSH-2.0-Go
2022-10-23 01:16:54.082 - [Debug] [Connection] Attacker connected: 34.133.67.239 | Client Identification: SSH-2.0-Go
2022-10-23 01:16:54.082 - [Debug] [Connection] Attacker connected: 34.133.67.239 | Client Identification: SSH-2.0-Go
2022-10-23 01:16:54.083 - [Debug] [Connection] Attacker connected: 34.133.67.239 | Client Identification: SSH-2.0-Go
2022-10-23 01:16:54.083 - [Debug] [Connection] Attacker connected: 34.133.67.239 | Client Identification: SSH-2.0-Go
2022-10-23 01:16:54.083 - [Debug] [Connection] Attacker connected: 34.133.67.239 | Client Identification: SSH-2.0-Go
2022-10-23 01:16:54.083 - [Debug] [Connection] Attacker connected: 34.133.67.239 | Client Identification: SSH-2.0-Go
2022-10-23 01:16:55.605 - [Debug] [Connection] Attacker connected: 34.133.67.239 | Client Identification: SSH-2.0-Go
2022-10-23 01:16:58.498 - [Debug] [Connection] Attacker connected: 34.133.67.239 | Client Identification: SSH-2.0-Go
2022-10-23 01:17:10.544 - [Debug] [Auth] Attacker 34.133.67.239 trying to authenticate with 'none'
2022-10-23 01:17:10.544 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-23 01:17:10.584 - [Debug] [Auth] Attacker 34.133.67.239 trying to authenticate with 'none'
2022-10-23 01:17:10.584 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-23 01:17:10.587 - [Debug] [Auth] Attacker 34.133.67.239 trying to authenticate with 'none'
2022-10-23 01:17:10.587 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-23 01:17:10.595 - [Debug] [Auth] Attacker 34.133.67.239 trying to authenticate with 'none'
2022-10-23 01:17:10.595 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-23 01:17:13.786 - [Debug] [Auth] Attacker 34.133.67.239 trying to authenticate with 'none'
2022-10-23 01:17:13.786 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-23 01:17:18.700 - [Debug] [Auth] Attacker 34.133.67.239 trying to authenticate with 'password'
2022-10-23 01:17:18.701 - [Debug] [Auto Access] Attacker: 34.133.67.239, Threshold: 1, Attempts: 1
2022-10-23 01:17:18.701 - [Debug] [Auto Access] Compromising the honeypot
2022-10-23 01:17:18.701 - [Debug] [Auto Access] Adding the following credentials: 'root:qwerty'
2022-10-23 01:17:18.759 - [Debug] [Auto Access] Auto-access is now disabled for the remainder of this MITM server instance
2022-10-23 01:17:18.760 - [Debug] [Auth] Valid credentials - Password Authentication
2022-10-23 01:17:18.760 - [Debug] [LXC] Attempting to connect to the honeypot: 10.0.3.155
2022-10-23 01:17:18.764 - [Debug] [Auth] Attacker 34.133.67.239 trying to authenticate with 'password'
2022-10-23 01:17:18.765 - [Debug] [Auth] Attacker authentication error: Invalid credentials - Password Authentication Failure
2022-10-23 01:17:18.766 - [Debug] [Auth] Attacker: 34.133.67.239 has so far made 1 attempts. Remaining: 5 attempts
2022-10-23 01:17:18.766 - [Debug] [Auth] Attacker 34.133.67.239 trying to authenticate with 'password'
2022-10-23 01:17:18.766 - [Debug] [Auth] Attacker authentication error: Invalid credentials - Password Authentication Failure
2022-10-23 01:17:18.767 - [Debug] [Auth] Attacker: 34.133.67.239 has so far made 1 attempts. Remaining: 5 attempts
2022-10-23 01:17:18.767 - [Debug] [Auth] Attacker 34.133.67.239 trying to authenticate with 'password'
2022-10-23 01:17:18.767 - [Debug] [Auth] Attacker authentication error: Invalid credentials - User does not exist
2022-10-23 01:17:18.768 - [Debug] [Auth] Attacker: 34.133.67.239 has so far made 1 attempts. Remaining: 5 attempts
2022-10-23 01:17:18.813 - [Debug] [LXC-Auth] Attacker authenticated and is inside container
2022-10-23 01:17:23.228 - [Debug] [Auth] Attacker 34.133.67.239 trying to authenticate with 'password'
2022-10-23 01:17:23.229 - [Debug] [Auth] Attacker authentication error: Invalid credentials - User does not exist
2022-10-23 01:17:23.229 - [Debug] [Auth] Attacker: 34.133.67.239 has so far made 1 attempts. Remaining: 5 attempts
2022-10-23 01:17:32.736 - [Debug] [Connection] Attacker closed the connection
2022-10-23 01:17:32.748 - [Debug] [Connection] Attacker closed the connection
2022-10-23 01:17:32.748 - [Debug] [Connection] Attacker closed the connection
