
Started with the following options:
{
  debug: true,
  mitmIp: '10.0.3.1',
  autoAccess: true,
  autoAccessCache: 5000,
  maxAttemptsPerConnection: 6,
  sshServerIdentifier: 'SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2',
  containerMountPathPrefix: '/var/lib/lxc',
  containerMountPathSuffix: 'rootfs/',
  loggingAttackerStreams: '/home/student/MITM/logs/session_streams',
  loggingAuthenticationAttempts: '/home/student/MITM/logs/authentication_attempts',
  loggingLogins: '/home/student/MITM/logs/logins',
  loggingKeystrokes: '/home/student/MITM/logs/keystrokes',
  containerName: 'DATABASE_2',
  containerIp: '10.0.3.246',
  mitmPort: 1001,
  autoAccessFixed: 1
}
2022-10-25 00:03:56.842 - [Info] MITM Version: 2
2022-10-25 00:03:56.856 - [Info] Auto Access Enabled: true
2022-10-25 00:03:56.858 - [Debug] [Init] Auto Access Theshold Achieved: false
2022-10-25 00:03:56.906 - [Info] SSH man-in-the-middle server for 10.0.3.246 listening on 10.0.3.1:1001
2022-10-25 00:03:57.295 - [Debug] [Connection] Attacker connected: 157.245.137.18 | Client Identification: SSH-2.0-Go
2022-10-25 00:03:57.405 - [Debug] [Auth] Attacker 157.245.137.18 trying to authenticate with 'none'
2022-10-25 00:03:57.405 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-25 00:03:57.499 - [Debug] [Auth] Attacker 157.245.137.18 trying to authenticate with 'publickey'
2022-10-25 00:03:57.501 - [Debug] [Auth] Attacker authentication error: Publickey authentication failed
2022-10-25 00:03:57.501 - [Debug] [Auth] Attacker: 157.245.137.18 has so far made 1 attempts. Remaining: 5 attempts
2022-10-25 00:03:57.587 - [Debug] [Connection] Attacker closed the connection
2022-10-25 00:03:57.631 - [Debug] [Connection] Attacker connected: 157.245.137.18 | Client Identification: SSH-2.0-Go
2022-10-25 00:03:57.784 - [Debug] [Auth] Attacker 157.245.137.18 trying to authenticate with 'none'
2022-10-25 00:03:57.785 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-25 00:03:57.849 - [Debug] [Auth] Attacker 157.245.137.18 trying to authenticate with 'password'
2022-10-25 00:03:57.850 - [Debug] [Auto Access] Attacker: 157.245.137.18, Threshold: 1, Attempts: 1
2022-10-25 00:03:57.850 - [Debug] [Auto Access] Compromising the honeypot
2022-10-25 00:03:57.850 - [Debug] [Auto Access] Adding the following credentials: 'root:1'
{"level":"error","message":"Forever detected script was killed by signal: SIGKILL"}
